package main

//Autogenerated with JSON TO Go

type Base16 struct {
	// Metadata
	Scheme string `json:"scheme"`
	Type   string `json:"type"`
	Author string `json:"author"`
	Base00 string `json:"base00"`
	Base01 string `json:"base01"`
	Base02 string `json:"base02"`
	Base03 string `json:"base03"`
	Base04 string `json:"base04"`
	Base05 string `json:"base05"`
	Base06 string `json:"base06"`
	Base07 string `json:"base07"`
	Base08 string `json:"base08"`
	Base09 string `json:"base09"`
	Base0A string `json:"base0A"`
	Base0B string `json:"base0B"`
	Base0C string `json:"base0C"`
	Base0D string `json:"base0D"`
	Base0E string `json:"base0E"`
	Base0F string `json:"base0F"`
}

type VsCodeTheme struct {
	Name                 string   `json:"name"`
	Type                 string   `json:"type"`
	SemanticHighlighting bool     `json:"semanticHighlighting"`
	Colors               VSColors `json:"colors"`
}
