package vsc

import (
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"path"

	"github.com/tailscale/hujson"
)

// The Default vscode themes
// go:embed themes/vscode
var defaultThemes embed.FS

type Extension struct {
	// Extension folder
	path string

	// Auto generated by https://transform.tools/json-to-go
	Name        string   `json:"name"`
	DisplayName string   `json:"displayName"`
	Description string   `json:"description"`
	Publisher   string   `json:"publisher"`
	Version     string   `json:"version"`
	Categories  []string `json:"categories"`
	Icon        string   `json:"icon"`

	Engines struct {
		Vscode string `json:"vscode"`
	} `json:"engines"`

	Author struct {
		Name  string `json:"name"`
		Email string `json:"email"`
	} `json:"author"`

	Repository struct {
		URL  string `json:"url"`
		Type string `json:"type"`
	} `json:"repository"`

	Contributes struct {
		Themes []struct {
			Label   string `json:"label"`
			UITheme string `json:"uiTheme"`
			Path    string `json:"path"`
		} `json:"themes"`
	} `json:"contributes"`

	Metadata struct {
		ID                   string `json:"id"`
		PublisherID          string `json:"publisherId"`
		PublisherDisplayName string `json:"publisherDisplayName"`
		InstalledTimestamp   int64  `json:"installedTimestamp"`
	} `json:"__metadata"`
}

// Decode package.json to struct
func (e Extension) ParsePakageJson() {
}

//
// Unmarshal json theme to string
func (e Extension) GetThemes() []VsCodeTheme {
	// func parseThemes(s string) []VsCodeTheme {
	var v VsCodeTheme
	var p PackageJson
	var result []VsCodeTheme

	filename := path.Join(e.path, "package.json")
	f, err := os.ReadFile(filename)
	if err != nil {
		fmt.Print(err)
		os.Exit(1)
	}

	err = json.Unmarshal(f, &p)
	if err != nil {
		fmt.Print(err)
		os.Exit(1)
	}
	for _, theme := range p.Contributes.Themes {

		tpath := path.Join(e.path, theme.Path)
		t, err := os.ReadFile(tpath)
		if err != nil {
			fmt.Println("error opening theme file", tpath)
			continue
		}
		ast, err := hujson.Parse(t)
		if err != nil {
			fmt.Println("error parsing theme file(hujson)", tpath)
			continue
		}
		ast.Standardize()
		t = ast.Pack()
		err = json.Unmarshal(t, &v)
		if err != nil {
			fmt.Println("error unmarshalling json", tpath)
			continue
		}
		err = json.Unmarshal(t, &v)
		if err != nil {
			fmt.Println("error parsing json file in ", theme.Path, err)
			continue
		} else {
			v.Name = theme.Label
			v.Type = theme.UITheme
			result = append(result, v)
		}
	}
	return result

}

type AutoGenerated struct {
	Schema string `json:"$schema"`
	Type   string `json:"type"`
	Colors struct {
		ActivityBarBadgeBackground                        string `json:"activityBarBadge.background"`
		EditorBackground                                  string `json:"editor.background"`
		EditorForeground                                  string `json:"editor.foreground"`
		EditorInactiveSelectionBackground                 string `json:"editor.inactiveSelectionBackground"`
		EditorSelectionHighlightBackground                string `json:"editor.selectionHighlightBackground"`
		EditorIndentGuideActiveBackground                 string `json:"editorIndentGuide.activeBackground"`
		EditorIndentGuideBackground                       string `json:"editorIndentGuide.background"`
		InputPlaceholderForeground                        string `json:"input.placeholderForeground"`
		ListActiveSelectionIconForeground                 string `json:"list.activeSelectionIconForeground"`
		ListDropBackground                                string `json:"list.dropBackground"`
		MenuBackground                                    string `json:"menu.background"`
		MenuForeground                                    string `json:"menu.foreground"`
		PortsIconRunningProcessForeground                 string `json:"ports.iconRunningProcessForeground"`
		SideBarSectionHeaderBackground                    string `json:"sideBarSectionHeader.background"`
		SideBarSectionHeaderBorder                        string `json:"sideBarSectionHeader.border"`
		SideBarTitleForeground                            string `json:"sideBarTitle.foreground"`
		StatusBarItemRemoteBackground                     string `json:"statusBarItem.remoteBackground"`
		StatusBarItemRemoteForeground                     string `json:"statusBarItem.remoteForeground"`
		TabLastPinnedBorder                               string `json:"tab.lastPinnedBorder"`
		ActivityBarActiveBorder                           string `json:"activityBar.activeBorder"`
		ActivityBarBackground                             string `json:"activityBar.background"`
		ActivityBarDropBorder                             string `json:"activityBar.dropBorder"`
		ActivityBarForeground                             string `json:"activityBar.foreground"`
		ActivityBarInactiveForeground                     string `json:"activityBar.inactiveForeground"`
		ActivityBarBadgeForeground                        string `json:"activityBarBadge.foreground"`
		BadgeBackground                                   string `json:"badge.background"`
		BadgeForeground                                   string `json:"badge.foreground"`
		BannerBackground                                  string `json:"banner.background"`
		BannerForeground                                  string `json:"banner.foreground"`
		BannerIconForeground                              string `json:"banner.iconForeground"`
		BreadcrumbActiveSelectionForeground               string `json:"breadcrumb.activeSelectionForeground"`
		BreadcrumbBackground                              string `json:"breadcrumb.background"`
		BreadcrumbFocusForeground                         string `json:"breadcrumb.focusForeground"`
		BreadcrumbForeground                              string `json:"breadcrumb.foreground"`
		BreadcrumbPickerBackground                        string `json:"breadcrumbPicker.background"`
		ButtonBackground                                  string `json:"button.background"`
		ButtonForeground                                  string `json:"button.foreground"`
		ButtonHoverBackground                             string `json:"button.hoverBackground"`
		ButtonSecondaryBackground                         string `json:"button.secondaryBackground"`
		ButtonSecondaryForeground                         string `json:"button.secondaryForeground"`
		ButtonSecondaryHoverBackground                    string `json:"button.secondaryHoverBackground"`
		ChartsBlue                                        string `json:"charts.blue"`
		ChartsForeground                                  string `json:"charts.foreground"`
		ChartsGreen                                       string `json:"charts.green"`
		ChartsLines                                       string `json:"charts.lines"`
		ChartsOrange                                      string `json:"charts.orange"`
		ChartsPurple                                      string `json:"charts.purple"`
		ChartsRed                                         string `json:"charts.red"`
		ChartsYellow                                      string `json:"charts.yellow"`
		CheckboxBackground                                string `json:"checkbox.background"`
		CheckboxBorder                                    string `json:"checkbox.border"`
		CheckboxForeground                                string `json:"checkbox.foreground"`
		DebugConsoleErrorForeground                       string `json:"debugConsole.errorForeground"`
		DebugConsoleInfoForeground                        string `json:"debugConsole.infoForeground"`
		DebugConsoleSourceForeground                      string `json:"debugConsole.sourceForeground"`
		DebugConsoleWarningForeground                     string `json:"debugConsole.warningForeground"`
		DebugConsoleInputIconForeground                   string `json:"debugConsoleInputIcon.foreground"`
		DebugExceptionWidgetBackground                    string `json:"debugExceptionWidget.background"`
		DebugExceptionWidgetBorder                        string `json:"debugExceptionWidget.border"`
		DebugIconBreakpointCurrentStackframeForeground    string `json:"debugIcon.breakpointCurrentStackframeForeground"`
		DebugIconBreakpointDisabledForeground             string `json:"debugIcon.breakpointDisabledForeground"`
		DebugIconBreakpointForeground                     string `json:"debugIcon.breakpointForeground"`
		DebugIconBreakpointStackframeForeground           string `json:"debugIcon.breakpointStackframeForeground"`
		DebugIconBreakpointUnverifiedForeground           string `json:"debugIcon.breakpointUnverifiedForeground"`
		DebugIconContinueForeground                       string `json:"debugIcon.continueForeground"`
		DebugIconDisconnectForeground                     string `json:"debugIcon.disconnectForeground"`
		DebugIconPauseForeground                          string `json:"debugIcon.pauseForeground"`
		DebugIconRestartForeground                        string `json:"debugIcon.restartForeground"`
		DebugIconStartForeground                          string `json:"debugIcon.startForeground"`
		DebugIconStepBackForeground                       string `json:"debugIcon.stepBackForeground"`
		DebugIconStepIntoForeground                       string `json:"debugIcon.stepIntoForeground"`
		DebugIconStepOutForeground                        string `json:"debugIcon.stepOutForeground"`
		DebugIconStepOverForeground                       string `json:"debugIcon.stepOverForeground"`
		DebugIconStopForeground                           string `json:"debugIcon.stopForeground"`
		DebugTokenExpressionBoolean                       string `json:"debugTokenExpression.boolean"`
		DebugTokenExpressionError                         string `json:"debugTokenExpression.error"`
		DebugTokenExpressionName                          string `json:"debugTokenExpression.name"`
		DebugTokenExpressionNumber                        string `json:"debugTokenExpression.number"`
		DebugTokenExpressionString                        string `json:"debugTokenExpression.string"`
		DebugTokenExpressionValue                         string `json:"debugTokenExpression.value"`
		DebugToolBarBackground                            string `json:"debugToolBar.background"`
		DebugViewExceptionLabelBackground                 string `json:"debugView.exceptionLabelBackground"`
		DebugViewExceptionLabelForeground                 string `json:"debugView.exceptionLabelForeground"`
		DebugViewStateLabelBackground                     string `json:"debugView.stateLabelBackground"`
		DebugViewStateLabelForeground                     string `json:"debugView.stateLabelForeground"`
		DebugViewValueChangedHighlight                    string `json:"debugView.valueChangedHighlight"`
		DescriptionForeground                             string `json:"descriptionForeground"`
		DiffEditorDiagonalFill                            string `json:"diffEditor.diagonalFill"`
		DiffEditorInsertedTextBackground                  string `json:"diffEditor.insertedTextBackground"`
		DiffEditorRemovedTextBackground                   string `json:"diffEditor.removedTextBackground"`
		DropdownBackground                                string `json:"dropdown.background"`
		DropdownBorder                                    string `json:"dropdown.border"`
		DropdownForeground                                string `json:"dropdown.foreground"`
		EditorFindMatchBackground                         string `json:"editor.findMatchBackground"`
		EditorFindMatchHighlightBackground                string `json:"editor.findMatchHighlightBackground"`
		EditorFindRangeHighlightBackground                string `json:"editor.findRangeHighlightBackground"`
		EditorFocusedStackFrameHighlightBackground        string `json:"editor.focusedStackFrameHighlightBackground"`
		EditorFoldBackground                              string `json:"editor.foldBackground"`
		EditorHoverHighlightBackground                    string `json:"editor.hoverHighlightBackground"`
		EditorInlineValuesBackground                      string `json:"editor.inlineValuesBackground"`
		EditorInlineValuesForeground                      string `json:"editor.inlineValuesForeground"`
		EditorLineHighlightBorder                         string `json:"editor.lineHighlightBorder"`
		EditorLinkedEditingBackground                     string `json:"editor.linkedEditingBackground"`
		EditorRangeHighlightBackground                    string `json:"editor.rangeHighlightBackground"`
		EditorSelectionBackground                         string `json:"editor.selectionBackground"`
		EditorSnippetFinalTabstopHighlightBorder          string `json:"editor.snippetFinalTabstopHighlightBorder"`
		EditorSnippetTabstopHighlightBackground           string `json:"editor.snippetTabstopHighlightBackground"`
		EditorStackFrameHighlightBackground               string `json:"editor.stackFrameHighlightBackground"`
		EditorSymbolHighlightBackground                   string `json:"editor.symbolHighlightBackground"`
		EditorWordHighlightBackground                     string `json:"editor.wordHighlightBackground"`
		EditorWordHighlightStrongBackground               string `json:"editor.wordHighlightStrongBackground"`
		EditorActiveLineNumberForeground                  string `json:"editorActiveLineNumber.foreground"`
		EditorBracketHighlightForeground1                 string `json:"editorBracketHighlight.foreground1"`
		EditorBracketHighlightForeground2                 string `json:"editorBracketHighlight.foreground2"`
		EditorBracketHighlightForeground3                 string `json:"editorBracketHighlight.foreground3"`
		EditorBracketHighlightForeground4                 string `json:"editorBracketHighlight.foreground4"`
		EditorBracketHighlightForeground5                 string `json:"editorBracketHighlight.foreground5"`
		EditorBracketHighlightForeground6                 string `json:"editorBracketHighlight.foreground6"`
		EditorBracketHighlightUnexpectedBracketForeground string `json:"editorBracketHighlight.unexpectedBracket.foreground"`
		EditorBracketMatchBackground                      string `json:"editorBracketMatch.background"`
		EditorBracketMatchBorder                          string `json:"editorBracketMatch.border"`
		EditorBracketPairGuideActiveBackground1           string `json:"editorBracketPairGuide.activeBackground1"`
		EditorBracketPairGuideActiveBackground2           string `json:"editorBracketPairGuide.activeBackground2"`
		EditorBracketPairGuideActiveBackground3           string `json:"editorBracketPairGuide.activeBackground3"`
		EditorBracketPairGuideActiveBackground4           string `json:"editorBracketPairGuide.activeBackground4"`
		EditorBracketPairGuideActiveBackground5           string `json:"editorBracketPairGuide.activeBackground5"`
		EditorBracketPairGuideActiveBackground6           string `json:"editorBracketPairGuide.activeBackground6"`
		EditorBracketPairGuideBackground1                 string `json:"editorBracketPairGuide.background1"`
		EditorBracketPairGuideBackground2                 string `json:"editorBracketPairGuide.background2"`
		EditorBracketPairGuideBackground3                 string `json:"editorBracketPairGuide.background3"`
		EditorBracketPairGuideBackground4                 string `json:"editorBracketPairGuide.background4"`
		EditorBracketPairGuideBackground5                 string `json:"editorBracketPairGuide.background5"`
		EditorBracketPairGuideBackground6                 string `json:"editorBracketPairGuide.background6"`
		EditorCodeLensForeground                          string `json:"editorCodeLens.foreground"`
		EditorCursorForeground                            string `json:"editorCursor.foreground"`
		EditorErrorForeground                             string `json:"editorError.foreground"`
		EditorGhostTextForeground                         string `json:"editorGhostText.foreground"`
		EditorGroupBorder                                 string `json:"editorGroup.border"`
		EditorGroupDropBackground                         string `json:"editorGroup.dropBackground"`
		EditorGroupHeaderNoTabsBackground                 string `json:"editorGroupHeader.noTabsBackground"`
		EditorGroupHeaderTabsBackground                   string `json:"editorGroupHeader.tabsBackground"`
		EditorGutterAddedBackground                       string `json:"editorGutter.addedBackground"`
		EditorGutterBackground                            string `json:"editorGutter.background"`
		EditorGutterCommentRangeForeground                string `json:"editorGutter.commentRangeForeground"`
		EditorGutterDeletedBackground                     string `json:"editorGutter.deletedBackground"`
		EditorGutterFoldingControlForeground              string `json:"editorGutter.foldingControlForeground"`
		EditorGutterModifiedBackground                    string `json:"editorGutter.modifiedBackground"`
		EditorHintForeground                              string `json:"editorHint.foreground"`
		EditorHoverWidgetBackground                       string `json:"editorHoverWidget.background"`
		EditorHoverWidgetBorder                           string `json:"editorHoverWidget.border"`
		EditorHoverWidgetForeground                       string `json:"editorHoverWidget.foreground"`
		EditorHoverWidgetHighlightForeground              string `json:"editorHoverWidget.highlightForeground"`
		EditorHoverWidgetStatusBarBackground              string `json:"editorHoverWidget.statusBarBackground"`
		EditorInfoForeground                              string `json:"editorInfo.foreground"`
		EditorInlayHintBackground                         string `json:"editorInlayHint.background"`
		EditorInlayHintForeground                         string `json:"editorInlayHint.foreground"`
		EditorInlayHintParameterBackground                string `json:"editorInlayHint.parameterBackground"`
		EditorInlayHintParameterForeground                string `json:"editorInlayHint.parameterForeground"`
		EditorInlayHintTypeBackground                     string `json:"editorInlayHint.typeBackground"`
		EditorInlayHintTypeForeground                     string `json:"editorInlayHint.typeForeground"`
		EditorLightBulbForeground                         string `json:"editorLightBulb.foreground"`
		EditorLightBulbAutoFixForeground                  string `json:"editorLightBulbAutoFix.foreground"`
		EditorLineNumberActiveForeground                  string `json:"editorLineNumber.activeForeground"`
		EditorLineNumberForeground                        string `json:"editorLineNumber.foreground"`
		EditorLinkActiveForeground                        string `json:"editorLink.activeForeground"`
		EditorMarkerNavigationBackground                  string `json:"editorMarkerNavigation.background"`
		EditorMarkerNavigationErrorBackground             string `json:"editorMarkerNavigationError.background"`
		EditorMarkerNavigationErrorHeaderBackground       string `json:"editorMarkerNavigationError.headerBackground"`
		EditorMarkerNavigationInfoBackground              string `json:"editorMarkerNavigationInfo.background"`
		EditorMarkerNavigationInfoHeaderBackground        string `json:"editorMarkerNavigationInfo.headerBackground"`
		EditorMarkerNavigationWarningBackground           string `json:"editorMarkerNavigationWarning.background"`
		EditorMarkerNavigationWarningHeaderBackground     string `json:"editorMarkerNavigationWarning.headerBackground"`
		EditorOverviewRulerAddedForeground                string `json:"editorOverviewRuler.addedForeground"`
		EditorOverviewRulerBorder                         string `json:"editorOverviewRuler.border"`
		EditorOverviewRulerBracketMatchForeground         string `json:"editorOverviewRuler.bracketMatchForeground"`
		EditorOverviewRulerCommonContentForeground        string `json:"editorOverviewRuler.commonContentForeground"`
		EditorOverviewRulerCurrentContentForeground       string `json:"editorOverviewRuler.currentContentForeground"`
		EditorOverviewRulerDeletedForeground              string `json:"editorOverviewRuler.deletedForeground"`
		EditorOverviewRulerErrorForeground                string `json:"editorOverviewRuler.errorForeground"`
		EditorOverviewRulerFindMatchForeground            string `json:"editorOverviewRuler.findMatchForeground"`
		EditorOverviewRulerIncomingContentForeground      string `json:"editorOverviewRuler.incomingContentForeground"`
		EditorOverviewRulerInfoForeground                 string `json:"editorOverviewRuler.infoForeground"`
		EditorOverviewRulerModifiedForeground             string `json:"editorOverviewRuler.modifiedForeground"`
		EditorOverviewRulerRangeHighlightForeground       string `json:"editorOverviewRuler.rangeHighlightForeground"`
		EditorOverviewRulerSelectionHighlightForeground   string `json:"editorOverviewRuler.selectionHighlightForeground"`
		EditorOverviewRulerUnicodeForeground              string `json:"editorOverviewRuler.unicodeForeground"`
		EditorOverviewRulerWarningForeground              string `json:"editorOverviewRuler.warningForeground"`
		EditorOverviewRulerWordHighlightForeground        string `json:"editorOverviewRuler.wordHighlightForeground"`
		EditorOverviewRulerWordHighlightStrongForeground  string `json:"editorOverviewRuler.wordHighlightStrongForeground"`
		EditorPaneBackground                              string `json:"editorPane.background"`
		EditorRulerForeground                             string `json:"editorRuler.foreground"`
		EditorSuggestWidgetBackground                     string `json:"editorSuggestWidget.background"`
		EditorSuggestWidgetBorder                         string `json:"editorSuggestWidget.border"`
		EditorSuggestWidgetFocusHighlightForeground       string `json:"editorSuggestWidget.focusHighlightForeground"`
		EditorSuggestWidgetForeground                     string `json:"editorSuggestWidget.foreground"`
		EditorSuggestWidgetHighlightForeground            string `json:"editorSuggestWidget.highlightForeground"`
		EditorSuggestWidgetSelectedBackground             string `json:"editorSuggestWidget.selectedBackground"`
		EditorSuggestWidgetSelectedForeground             string `json:"editorSuggestWidget.selectedForeground"`
		EditorSuggestWidgetSelectedIconForeground         string `json:"editorSuggestWidget.selectedIconForeground"`
		EditorSuggestWidgetStatusForeground               string `json:"editorSuggestWidgetStatus.foreground"`
		EditorUnicodeHighlightBorder                      string `json:"editorUnicodeHighlight.border"`
		EditorUnnecessaryCodeOpacity                      string `json:"editorUnnecessaryCode.opacity"`
		EditorWarningForeground                           string `json:"editorWarning.foreground"`
		EditorWhitespaceForeground                        string `json:"editorWhitespace.foreground"`
		EditorWidgetBackground                            string `json:"editorWidget.background"`
		EditorWidgetBorder                                string `json:"editorWidget.border"`
		EditorWidgetForeground                            string `json:"editorWidget.foreground"`
		ErrorForeground                                   string `json:"errorForeground"`
		ExtensionBadgeRemoteBackground                    string `json:"extensionBadge.remoteBackground"`
		ExtensionBadgeRemoteForeground                    string `json:"extensionBadge.remoteForeground"`
		ExtensionButtonProminentBackground                string `json:"extensionButton.prominentBackground"`
		ExtensionButtonProminentForeground                string `json:"extensionButton.prominentForeground"`
		ExtensionButtonProminentHoverBackground           string `json:"extensionButton.prominentHoverBackground"`
		ExtensionIconPreReleaseForeground                 string `json:"extensionIcon.preReleaseForeground"`
		ExtensionIconStarForeground                       string `json:"extensionIcon.starForeground"`
		ExtensionIconVerifiedForeground                   string `json:"extensionIcon.verifiedForeground"`
		FocusBorder                                       string `json:"focusBorder"`
		Foreground                                        string `json:"foreground"`
		GitDecorationAddedResourceForeground              string `json:"gitDecoration.addedResourceForeground"`
		GitDecorationConflictingResourceForeground        string `json:"gitDecoration.conflictingResourceForeground"`
		GitDecorationDeletedResourceForeground            string `json:"gitDecoration.deletedResourceForeground"`
		GitDecorationIgnoredResourceForeground            string `json:"gitDecoration.ignoredResourceForeground"`
		GitDecorationModifiedResourceForeground           string `json:"gitDecoration.modifiedResourceForeground"`
		GitDecorationRenamedResourceForeground            string `json:"gitDecoration.renamedResourceForeground"`
		GitDecorationStageDeletedResourceForeground       string `json:"gitDecoration.stageDeletedResourceForeground"`
		GitDecorationStageModifiedResourceForeground      string `json:"gitDecoration.stageModifiedResourceForeground"`
		GitDecorationSubmoduleResourceForeground          string `json:"gitDecoration.submoduleResourceForeground"`
		GitDecorationUntrackedResourceForeground          string `json:"gitDecoration.untrackedResourceForeground"`
		IconForeground                                    string `json:"icon.foreground"`
		InputBackground                                   string `json:"input.background"`
		InputForeground                                   string `json:"input.foreground"`
		InputOptionActiveBackground                       string `json:"inputOption.activeBackground"`
		InputOptionActiveBorder                           string `json:"inputOption.activeBorder"`
		InputOptionActiveForeground                       string `json:"inputOption.activeForeground"`
		InputOptionHoverBackground                        string `json:"inputOption.hoverBackground"`
		InputValidationErrorBackground                    string `json:"inputValidation.errorBackground"`
		InputValidationErrorBorder                        string `json:"inputValidation.errorBorder"`
		InputValidationInfoBackground                     string `json:"inputValidation.infoBackground"`
		InputValidationInfoBorder                         string `json:"inputValidation.infoBorder"`
		InputValidationWarningBackground                  string `json:"inputValidation.warningBackground"`
		InputValidationWarningBorder                      string `json:"inputValidation.warningBorder"`
		InteractiveActiveCodeBorder                       string `json:"interactive.activeCodeBorder"`
		InteractiveInactiveCodeBorder                     string `json:"interactive.inactiveCodeBorder"`
		KeybindingLabelBackground                         string `json:"keybindingLabel.background"`
		KeybindingLabelBorder                             string `json:"keybindingLabel.border"`
		KeybindingLabelBottomBorder                       string `json:"keybindingLabel.bottomBorder"`
		KeybindingLabelForeground                         string `json:"keybindingLabel.foreground"`
		KeybindingTableHeaderBackground                   string `json:"keybindingTable.headerBackground"`
		KeybindingTableRowsBackground                     string `json:"keybindingTable.rowsBackground"`
		ListActiveSelectionBackground                     string `json:"list.activeSelectionBackground"`
		ListActiveSelectionForeground                     string `json:"list.activeSelectionForeground"`
		ListDeemphasizedForeground                        string `json:"list.deemphasizedForeground"`
		ListErrorForeground                               string `json:"list.errorForeground"`
		ListFilterMatchBackground                         string `json:"list.filterMatchBackground"`
		ListFocusHighlightForeground                      string `json:"list.focusHighlightForeground"`
		ListFocusOutline                                  string `json:"list.focusOutline"`
		ListHighlightForeground                           string `json:"list.highlightForeground"`
		ListHoverBackground                               string `json:"list.hoverBackground"`
		ListInactiveSelectionBackground                   string `json:"list.inactiveSelectionBackground"`
		ListInvalidItemForeground                         string `json:"list.invalidItemForeground"`
		ListWarningForeground                             string `json:"list.warningForeground"`
		ListFilterWidgetBackground                        string `json:"listFilterWidget.background"`
		ListFilterWidgetNoMatchesOutline                  string `json:"listFilterWidget.noMatchesOutline"`
		ListFilterWidgetOutline                           string `json:"listFilterWidget.outline"`
		MenuSelectionBackground                           string `json:"menu.selectionBackground"`
		MenuSelectionForeground                           string `json:"menu.selectionForeground"`
		MenuSeparatorBackground                           string `json:"menu.separatorBackground"`
		MenubarSelectionBackground                        string `json:"menubar.selectionBackground"`
		MenubarSelectionForeground                        string `json:"menubar.selectionForeground"`
		MergeCommonContentBackground                      string `json:"merge.commonContentBackground"`
		MergeCommonHeaderBackground                       string `json:"merge.commonHeaderBackground"`
		MergeCurrentContentBackground                     string `json:"merge.currentContentBackground"`
		MergeCurrentHeaderBackground                      string `json:"merge.currentHeaderBackground"`
		MergeIncomingContentBackground                    string `json:"merge.incomingContentBackground"`
		MergeIncomingHeaderBackground                     string `json:"merge.incomingHeaderBackground"`
		MinimapErrorHighlight                             string `json:"minimap.errorHighlight"`
		MinimapFindMatchHighlight                         string `json:"minimap.findMatchHighlight"`
		MinimapForegroundOpacity                          string `json:"minimap.foregroundOpacity"`
		MinimapSelectionHighlight                         string `json:"minimap.selectionHighlight"`
		MinimapSelectionOccurrenceHighlight               string `json:"minimap.selectionOccurrenceHighlight"`
		MinimapUnicodeHighlight                           string `json:"minimap.unicodeHighlight"`
		MinimapWarningHighlight                           string `json:"minimap.warningHighlight"`
		MinimapGutterAddedBackground                      string `json:"minimapGutter.addedBackground"`
		MinimapGutterDeletedBackground                    string `json:"minimapGutter.deletedBackground"`
		MinimapGutterModifiedBackground                   string `json:"minimapGutter.modifiedBackground"`
		MinimapSliderActiveBackground                     string `json:"minimapSlider.activeBackground"`
		MinimapSliderBackground                           string `json:"minimapSlider.background"`
		MinimapSliderHoverBackground                      string `json:"minimapSlider.hoverBackground"`
		NotebookCellBorderColor                           string `json:"notebook.cellBorderColor"`
		NotebookCellEditorBackground                      string `json:"notebook.cellEditorBackground"`
		NotebookCellInsertionIndicator                    string `json:"notebook.cellInsertionIndicator"`
		NotebookCellStatusBarItemHoverBackground          string `json:"notebook.cellStatusBarItemHoverBackground"`
		NotebookCellToolbarSeparator                      string `json:"notebook.cellToolbarSeparator"`
		NotebookFocusedCellBorder                         string `json:"notebook.focusedCellBorder"`
		NotebookFocusedEditorBorder                       string `json:"notebook.focusedEditorBorder"`
		NotebookInactiveFocusedCellBorder                 string `json:"notebook.inactiveFocusedCellBorder"`
		NotebookSelectedCellBackground                    string `json:"notebook.selectedCellBackground"`
		NotebookSelectedCellBorder                        string `json:"notebook.selectedCellBorder"`
		NotebookSymbolHighlightBackground                 string `json:"notebook.symbolHighlightBackground"`
		NotebookScrollbarSliderActiveBackground           string `json:"notebookScrollbarSlider.activeBackground"`
		NotebookScrollbarSliderBackground                 string `json:"notebookScrollbarSlider.background"`
		NotebookScrollbarSliderHoverBackground            string `json:"notebookScrollbarSlider.hoverBackground"`
		NotebookStatusErrorIconForeground                 string `json:"notebookStatusErrorIcon.foreground"`
		NotebookStatusRunningIconForeground               string `json:"notebookStatusRunningIcon.foreground"`
		NotebookStatusSuccessIconForeground               string `json:"notebookStatusSuccessIcon.foreground"`
		NotificationCenterHeaderBackground                string `json:"notificationCenterHeader.background"`
		NotificationLinkForeground                        string `json:"notificationLink.foreground"`
		NotificationsBackground                           string `json:"notifications.background"`
		NotificationsBorder                               string `json:"notifications.border"`
		NotificationsForeground                           string `json:"notifications.foreground"`
		NotificationsErrorIconForeground                  string `json:"notificationsErrorIcon.foreground"`
		NotificationsInfoIconForeground                   string `json:"notificationsInfoIcon.foreground"`
		NotificationsWarningIconForeground                string `json:"notificationsWarningIcon.foreground"`
		PanelBackground                                   string `json:"panel.background"`
		PanelBorder                                       string `json:"panel.border"`
		PanelDropBorder                                   string `json:"panel.dropBorder"`
		PanelSectionBorder                                string `json:"panelSection.border"`
		PanelSectionDropBackground                        string `json:"panelSection.dropBackground"`
		PanelSectionHeaderBackground                      string `json:"panelSectionHeader.background"`
		PanelTitleActiveBorder                            string `json:"panelTitle.activeBorder"`
		PanelTitleActiveForeground                        string `json:"panelTitle.activeForeground"`
		PanelTitleInactiveForeground                      string `json:"panelTitle.inactiveForeground"`
		PeekViewBorder                                    string `json:"peekView.border"`
		PeekViewEditorBackground                          string `json:"peekViewEditor.background"`
		PeekViewEditorMatchHighlightBackground            string `json:"peekViewEditor.matchHighlightBackground"`
		PeekViewEditorGutterBackground                    string `json:"peekViewEditorGutter.background"`
		PeekViewResultBackground                          string `json:"peekViewResult.background"`
		PeekViewResultFileForeground                      string `json:"peekViewResult.fileForeground"`
		PeekViewResultLineForeground                      string `json:"peekViewResult.lineForeground"`
		PeekViewResultMatchHighlightBackground            string `json:"peekViewResult.matchHighlightBackground"`
		PeekViewResultSelectionBackground                 string `json:"peekViewResult.selectionBackground"`
		PeekViewResultSelectionForeground                 string `json:"peekViewResult.selectionForeground"`
		PeekViewTitleBackground                           string `json:"peekViewTitle.background"`
		PeekViewTitleDescriptionForeground                string `json:"peekViewTitleDescription.foreground"`
		PeekViewTitleLabelForeground                      string `json:"peekViewTitleLabel.foreground"`
		PickerGroupBorder                                 string `json:"pickerGroup.border"`
		PickerGroupForeground                             string `json:"pickerGroup.foreground"`
		ProblemsErrorIconForeground                       string `json:"problemsErrorIcon.foreground"`
		ProblemsInfoIconForeground                        string `json:"problemsInfoIcon.foreground"`
		ProblemsWarningIconForeground                     string `json:"problemsWarningIcon.foreground"`
		ProgressBarBackground                             string `json:"progressBar.background"`
		QuickInputBackground                              string `json:"quickInput.background"`
		QuickInputForeground                              string `json:"quickInput.foreground"`
		QuickInputListFocusBackground                     string `json:"quickInputList.focusBackground"`
		QuickInputListFocusForeground                     string `json:"quickInputList.focusForeground"`
		QuickInputListFocusIconForeground                 string `json:"quickInputList.focusIconForeground"`
		QuickInputTitleBackground                         string `json:"quickInputTitle.background"`
		SashHoverBorder                                   string `json:"sash.hoverBorder"`
		ScmProviderBorder                                 string `json:"scm.providerBorder"`
		ScrollbarShadow                                   string `json:"scrollbar.shadow"`
		ScrollbarSliderActiveBackground                   string `json:"scrollbarSlider.activeBackground"`
		ScrollbarSliderBackground                         string `json:"scrollbarSlider.background"`
		ScrollbarSliderHoverBackground                    string `json:"scrollbarSlider.hoverBackground"`
		SearchEditorFindMatchBackground                   string `json:"searchEditor.findMatchBackground"`
		SettingsCheckboxBackground                        string `json:"settings.checkboxBackground"`
		SettingsCheckboxBorder                            string `json:"settings.checkboxBorder"`
		SettingsCheckboxForeground                        string `json:"settings.checkboxForeground"`
		SettingsDropdownBackground                        string `json:"settings.dropdownBackground"`
		SettingsDropdownBorder                            string `json:"settings.dropdownBorder"`
		SettingsDropdownForeground                        string `json:"settings.dropdownForeground"`
		SettingsDropdownListBorder                        string `json:"settings.dropdownListBorder"`
		SettingsFocusedRowBackground                      string `json:"settings.focusedRowBackground"`
		SettingsFocusedRowBorder                          string `json:"settings.focusedRowBorder"`
		SettingsHeaderForeground                          string `json:"settings.headerForeground"`
		SettingsModifiedItemIndicator                     string `json:"settings.modifiedItemIndicator"`
		SettingsNumberInputBackground                     string `json:"settings.numberInputBackground"`
		SettingsNumberInputForeground                     string `json:"settings.numberInputForeground"`
		SettingsRowHoverBackground                        string `json:"settings.rowHoverBackground"`
		SettingsTextInputBackground                       string `json:"settings.textInputBackground"`
		SettingsTextInputForeground                       string `json:"settings.textInputForeground"`
		SideBarBackground                                 string `json:"sideBar.background"`
		SideBarDropBackground                             string `json:"sideBar.dropBackground"`
		SideBySideEditorHorizontalBorder                  string `json:"sideBySideEditor.horizontalBorder"`
		SideBySideEditorVerticalBorder                    string `json:"sideBySideEditor.verticalBorder"`
		StatusBarBackground                               string `json:"statusBar.background"`
		StatusBarDebuggingBackground                      string `json:"statusBar.debuggingBackground"`
		StatusBarDebuggingForeground                      string `json:"statusBar.debuggingForeground"`
		StatusBarForeground                               string `json:"statusBar.foreground"`
		StatusBarNoFolderBackground                       string `json:"statusBar.noFolderBackground"`
		StatusBarNoFolderForeground                       string `json:"statusBar.noFolderForeground"`
		StatusBarItemActiveBackground                     string `json:"statusBarItem.activeBackground"`
		StatusBarItemErrorBackground                      string `json:"statusBarItem.errorBackground"`
		StatusBarItemErrorForeground                      string `json:"statusBarItem.errorForeground"`
		StatusBarItemHoverBackground                      string `json:"statusBarItem.hoverBackground"`
		StatusBarItemProminentBackground                  string `json:"statusBarItem.prominentBackground"`
		StatusBarItemProminentForeground                  string `json:"statusBarItem.prominentForeground"`
		StatusBarItemProminentHoverBackground             string `json:"statusBarItem.prominentHoverBackground"`
		StatusBarItemWarningBackground                    string `json:"statusBarItem.warningBackground"`
		StatusBarItemWarningForeground                    string `json:"statusBarItem.warningForeground"`
		SymbolIconArrayForeground                         string `json:"symbolIcon.arrayForeground"`
		SymbolIconBooleanForeground                       string `json:"symbolIcon.booleanForeground"`
		SymbolIconClassForeground                         string `json:"symbolIcon.classForeground"`
		SymbolIconColorForeground                         string `json:"symbolIcon.colorForeground"`
		SymbolIconConstantForeground                      string `json:"symbolIcon.constantForeground"`
		SymbolIconConstructorForeground                   string `json:"symbolIcon.constructorForeground"`
		SymbolIconEnumeratorForeground                    string `json:"symbolIcon.enumeratorForeground"`
		SymbolIconEnumeratorMemberForeground              string `json:"symbolIcon.enumeratorMemberForeground"`
		SymbolIconEventForeground                         string `json:"symbolIcon.eventForeground"`
		SymbolIconFieldForeground                         string `json:"symbolIcon.fieldForeground"`
		SymbolIconFileForeground                          string `json:"symbolIcon.fileForeground"`
		SymbolIconFolderForeground                        string `json:"symbolIcon.folderForeground"`
		SymbolIconFunctionForeground                      string `json:"symbolIcon.functionForeground"`
		SymbolIconInterfaceForeground                     string `json:"symbolIcon.interfaceForeground"`
		SymbolIconKeyForeground                           string `json:"symbolIcon.keyForeground"`
		SymbolIconKeywordForeground                       string `json:"symbolIcon.keywordForeground"`
		SymbolIconMethodForeground                        string `json:"symbolIcon.methodForeground"`
		SymbolIconModuleForeground                        string `json:"symbolIcon.moduleForeground"`
		SymbolIconNamespaceForeground                     string `json:"symbolIcon.namespaceForeground"`
		SymbolIconNullForeground                          string `json:"symbolIcon.nullForeground"`
		SymbolIconNumberForeground                        string `json:"symbolIcon.numberForeground"`
		SymbolIconObjectForeground                        string `json:"symbolIcon.objectForeground"`
		SymbolIconOperatorForeground                      string `json:"symbolIcon.operatorForeground"`
		SymbolIconPackageForeground                       string `json:"symbolIcon.packageForeground"`
		SymbolIconPropertyForeground                      string `json:"symbolIcon.propertyForeground"`
		SymbolIconReferenceForeground                     string `json:"symbolIcon.referenceForeground"`
		SymbolIconSnippetForeground                       string `json:"symbolIcon.snippetForeground"`
		SymbolIconStringForeground                        string `json:"symbolIcon.stringForeground"`
		SymbolIconStructForeground                        string `json:"symbolIcon.structForeground"`
		SymbolIconTextForeground                          string `json:"symbolIcon.textForeground"`
		SymbolIconTypeParameterForeground                 string `json:"symbolIcon.typeParameterForeground"`
		SymbolIconUnitForeground                          string `json:"symbolIcon.unitForeground"`
		SymbolIconVariableForeground                      string `json:"symbolIcon.variableForeground"`
		TabActiveBackground                               string `json:"tab.activeBackground"`
		TabActiveForeground                               string `json:"tab.activeForeground"`
		TabActiveModifiedBorder                           string `json:"tab.activeModifiedBorder"`
		TabBorder                                         string `json:"tab.border"`
		TabInactiveBackground                             string `json:"tab.inactiveBackground"`
		TabInactiveForeground                             string `json:"tab.inactiveForeground"`
		TabInactiveModifiedBorder                         string `json:"tab.inactiveModifiedBorder"`
		TabUnfocusedActiveBackground                      string `json:"tab.unfocusedActiveBackground"`
		TabUnfocusedActiveForeground                      string `json:"tab.unfocusedActiveForeground"`
		TabUnfocusedActiveModifiedBorder                  string `json:"tab.unfocusedActiveModifiedBorder"`
		TabUnfocusedInactiveBackground                    string `json:"tab.unfocusedInactiveBackground"`
		TabUnfocusedInactiveForeground                    string `json:"tab.unfocusedInactiveForeground"`
		TabUnfocusedInactiveModifiedBorder                string `json:"tab.unfocusedInactiveModifiedBorder"`
		TerminalAnsiBlack                                 string `json:"terminal.ansiBlack"`
		TerminalAnsiBlue                                  string `json:"terminal.ansiBlue"`
		TerminalAnsiBrightBlack                           string `json:"terminal.ansiBrightBlack"`
		TerminalAnsiBrightBlue                            string `json:"terminal.ansiBrightBlue"`
		TerminalAnsiBrightCyan                            string `json:"terminal.ansiBrightCyan"`
		TerminalAnsiBrightGreen                           string `json:"terminal.ansiBrightGreen"`
		TerminalAnsiBrightMagenta                         string `json:"terminal.ansiBrightMagenta"`
		TerminalAnsiBrightRed                             string `json:"terminal.ansiBrightRed"`
		TerminalAnsiBrightWhite                           string `json:"terminal.ansiBrightWhite"`
		TerminalAnsiBrightYellow                          string `json:"terminal.ansiBrightYellow"`
		TerminalAnsiCyan                                  string `json:"terminal.ansiCyan"`
		TerminalAnsiGreen                                 string `json:"terminal.ansiGreen"`
		TerminalAnsiMagenta                               string `json:"terminal.ansiMagenta"`
		TerminalAnsiRed                                   string `json:"terminal.ansiRed"`
		TerminalAnsiWhite                                 string `json:"terminal.ansiWhite"`
		TerminalAnsiYellow                                string `json:"terminal.ansiYellow"`
		TerminalBorder                                    string `json:"terminal.border"`
		TerminalDropBackground                            string `json:"terminal.dropBackground"`
		TerminalForeground                                string `json:"terminal.foreground"`
		TerminalSelectionBackground                       string `json:"terminal.selectionBackground"`
		TestingIconErrored                                string `json:"testing.iconErrored"`
		TestingIconFailed                                 string `json:"testing.iconFailed"`
		TestingIconPassed                                 string `json:"testing.iconPassed"`
		TestingIconQueued                                 string `json:"testing.iconQueued"`
		TestingIconSkipped                                string `json:"testing.iconSkipped"`
		TestingIconUnset                                  string `json:"testing.iconUnset"`
		TestingMessageErrorDecorationForeground           string `json:"testing.message.error.decorationForeground"`
		TestingMessageErrorLineBackground                 string `json:"testing.message.error.lineBackground"`
		TestingMessageInfoDecorationForeground            string `json:"testing.message.info.decorationForeground"`
		TestingPeekBorder                                 string `json:"testing.peekBorder"`
		TestingPeekHeaderBackground                       string `json:"testing.peekHeaderBackground"`
		TestingRunAction                                  string `json:"testing.runAction"`
		TextBlockQuoteBackground                          string `json:"textBlockQuote.background"`
		TextBlockQuoteBorder                              string `json:"textBlockQuote.border"`
		TextCodeBlockBackground                           string `json:"textCodeBlock.background"`
		TextLinkActiveForeground                          string `json:"textLink.activeForeground"`
		TextLinkForeground                                string `json:"textLink.foreground"`
		TextPreformatForeground                           string `json:"textPreformat.foreground"`
		TextSeparatorForeground                           string `json:"textSeparator.foreground"`
		TitleBarActiveBackground                          string `json:"titleBar.activeBackground"`
		TitleBarActiveForeground                          string `json:"titleBar.activeForeground"`
		TitleBarInactiveBackground                        string `json:"titleBar.inactiveBackground"`
		TitleBarInactiveForeground                        string `json:"titleBar.inactiveForeground"`
		ToolbarActiveBackground                           string `json:"toolbar.activeBackground"`
		ToolbarHoverBackground                            string `json:"toolbar.hoverBackground"`
		TreeIndentGuidesStroke                            string `json:"tree.indentGuidesStroke"`
		TreeTableColumnsBorder                            string `json:"tree.tableColumnsBorder"`
		TreeTableOddRowsBackground                        string `json:"tree.tableOddRowsBackground"`
		WelcomePageProgressBackground                     string `json:"welcomePage.progress.background"`
		WelcomePageProgressForeground                     string `json:"welcomePage.progress.foreground"`
		WelcomePageTileBackground                         string `json:"welcomePage.tileBackground"`
		WelcomePageTileHoverBackground                    string `json:"welcomePage.tileHoverBackground"`
		WelcomePageTileShadow                             string `json:"welcomePage.tileShadow"`
		WidgetShadow                                      string `json:"widget.shadow"`
		ActivityBarActiveBackground                       string `json:"activityBar.activeBackground"`
		ActivityBarActiveFocusBorder                      string `json:"activityBar.activeFocusBorder"`
		ActivityBarBorder                                 string `json:"activityBar.border"`
		ButtonBorder                                      string `json:"button.border"`
		ContrastActiveBorder                              string `json:"contrastActiveBorder"`
		ContrastBorder                                    string `json:"contrastBorder"`
		DebugToolBarBorder                                string `json:"debugToolBar.border"`
		DiffEditorBorder                                  string `json:"diffEditor.border"`
		DiffEditorInsertedTextBorder                      string `json:"diffEditor.insertedTextBorder"`
		DiffEditorRemovedTextBorder                       string `json:"diffEditor.removedTextBorder"`
		DropdownListBackground                            string `json:"dropdown.listBackground"`
		EditorFindMatchBorder                             string `json:"editor.findMatchBorder"`
		EditorFindMatchHighlightBorder                    string `json:"editor.findMatchHighlightBorder"`
		EditorFindRangeHighlightBorder                    string `json:"editor.findRangeHighlightBorder"`
		EditorLineHighlightBackground                     string `json:"editor.lineHighlightBackground"`
		EditorRangeHighlightBorder                        string `json:"editor.rangeHighlightBorder"`
		EditorSelectionForeground                         string `json:"editor.selectionForeground"`
		EditorSelectionHighlightBorder                    string `json:"editor.selectionHighlightBorder"`
		EditorSnippetFinalTabstopHighlightBackground      string `json:"editor.snippetFinalTabstopHighlightBackground"`
		EditorSnippetTabstopHighlightBorder               string `json:"editor.snippetTabstopHighlightBorder"`
		EditorSymbolHighlightBorder                       string `json:"editor.symbolHighlightBorder"`
		EditorWordHighlightBorder                         string `json:"editor.wordHighlightBorder"`
		EditorWordHighlightStrongBorder                   string `json:"editor.wordHighlightStrongBorder"`
		EditorCursorBackground                            string `json:"editorCursor.background"`
		EditorErrorBackground                             string `json:"editorError.background"`
		EditorErrorBorder                                 string `json:"editorError.border"`
		EditorGhostTextBackground                         string `json:"editorGhostText.background"`
		EditorGhostTextBorder                             string `json:"editorGhostText.border"`
		EditorGroupEmptyBackground                        string `json:"editorGroup.emptyBackground"`
		EditorGroupFocusedEmptyBorder                     string `json:"editorGroup.focusedEmptyBorder"`
		EditorGroupHeaderBorder                           string `json:"editorGroupHeader.border"`
		EditorGroupHeaderTabsBorder                       string `json:"editorGroupHeader.tabsBorder"`
		EditorHintBorder                                  string `json:"editorHint.border"`
		EditorInfoBackground                              string `json:"editorInfo.background"`
		EditorInfoBorder                                  string `json:"editorInfo.border"`
		EditorOverviewRulerBackground                     string `json:"editorOverviewRuler.background"`
		EditorUnnecessaryCodeBorder                       string `json:"editorUnnecessaryCode.border"`
		EditorWarningBackground                           string `json:"editorWarning.background"`
		EditorWarningBorder                               string `json:"editorWarning.border"`
		EditorWidgetResizeBorder                          string `json:"editorWidget.resizeBorder"`
		InputBorder                                       string `json:"input.border"`
		InputValidationErrorForeground                    string `json:"inputValidation.errorForeground"`
		InputValidationInfoForeground                     string `json:"inputValidation.infoForeground"`
		InputValidationWarningForeground                  string `json:"inputValidation.warningForeground"`
		ListFilterMatchBorder                             string `json:"list.filterMatchBorder"`
		ListFocusBackground                               string `json:"list.focusBackground"`
		ListFocusForeground                               string `json:"list.focusForeground"`
		ListHoverForeground                               string `json:"list.hoverForeground"`
		ListInactiveFocusBackground                       string `json:"list.inactiveFocusBackground"`
		ListInactiveFocusOutline                          string `json:"list.inactiveFocusOutline"`
		ListInactiveSelectionForeground                   string `json:"list.inactiveSelectionForeground"`
		ListInactiveSelectionIconForeground               string `json:"list.inactiveSelectionIconForeground"`
		MenuBorder                                        string `json:"menu.border"`
		MenuSelectionBorder                               string `json:"menu.selectionBorder"`
		MenubarSelectionBorder                            string `json:"menubar.selectionBorder"`
		MergeBorder                                       string `json:"merge.border"`
		MinimapBackground                                 string `json:"minimap.background"`
		NotebookCellHoverBackground                       string `json:"notebook.cellHoverBackground"`
		NotebookFocusedCellBackground                     string `json:"notebook.focusedCellBackground"`
		NotebookInactiveSelectedCellBorder                string `json:"notebook.inactiveSelectedCellBorder"`
		NotebookOutputContainerBackgroundColor            string `json:"notebook.outputContainerBackgroundColor"`
		NotebookOutputContainerBorderColor                string `json:"notebook.outputContainerBorderColor"`
		NotificationCenterBorder                          string `json:"notificationCenter.border"`
		NotificationCenterHeaderForeground                string `json:"notificationCenterHeader.foreground"`
		NotificationToastBorder                           string `json:"notificationToast.border"`
		PanelInputBorder                                  string `json:"panelInput.border"`
		PanelSectionHeaderBorder                          string `json:"panelSectionHeader.border"`
		PanelSectionHeaderForeground                      string `json:"panelSectionHeader.foreground"`
		PeekViewEditorMatchHighlightBorder                string `json:"peekViewEditor.matchHighlightBorder"`
		SearchEditorFindMatchBorder                       string `json:"searchEditor.findMatchBorder"`
		SearchEditorTextInputBorder                       string `json:"searchEditor.textInputBorder"`
		SelectionBackground                               string `json:"selection.background"`
		SettingsNumberInputBorder                         string `json:"settings.numberInputBorder"`
		SettingsTextInputBorder                           string `json:"settings.textInputBorder"`
		SideBarBorder                                     string `json:"sideBar.border"`
		SideBarForeground                                 string `json:"sideBar.foreground"`
		SideBarSectionHeaderForeground                    string `json:"sideBarSectionHeader.foreground"`
		StatusBarBorder                                   string `json:"statusBar.border"`
		StatusBarDebuggingBorder                          string `json:"statusBar.debuggingBorder"`
		StatusBarNoFolderBorder                           string `json:"statusBar.noFolderBorder"`
		TabActiveBorder                                   string `json:"tab.activeBorder"`
		TabActiveBorderTop                                string `json:"tab.activeBorderTop"`
		TabHoverBackground                                string `json:"tab.hoverBackground"`
		TabHoverBorder                                    string `json:"tab.hoverBorder"`
		TabHoverForeground                                string `json:"tab.hoverForeground"`
		TabUnfocusedActiveBorder                          string `json:"tab.unfocusedActiveBorder"`
		TabUnfocusedActiveBorderTop                       string `json:"tab.unfocusedActiveBorderTop"`
		TabUnfocusedHoverBackground                       string `json:"tab.unfocusedHoverBackground"`
		TabUnfocusedHoverBorder                           string `json:"tab.unfocusedHoverBorder"`
		TabUnfocusedHoverForeground                       string `json:"tab.unfocusedHoverForeground"`
		TerminalBackground                                string `json:"terminal.background"`
		TerminalTabActiveBorder                           string `json:"terminal.tab.activeBorder"`
		TerminalCursorBackground                          string `json:"terminalCursor.background"`
		TerminalCursorForeground                          string `json:"terminalCursor.foreground"`
		TestingMessageInfoLineBackground                  string `json:"testing.message.info.lineBackground"`
		TitleBarBorder                                    string `json:"titleBar.border"`
		ToolbarHoverOutline                               string `json:"toolbar.hoverOutline"`
		WalkThroughEmbeddedEditorBackground               string `json:"walkThrough.embeddedEditorBackground"`
		WelcomePageBackground                             string `json:"welcomePage.background"`
		WindowActiveBorder                                string `json:"window.activeBorder"`
		WindowInactiveBorder                              string `json:"window.inactiveBorder"`
	} `json:"colors"`
	TokenColors []struct {
		Scope    []string `json:"scope"`
		Settings struct {
			Foreground string `json:"foreground"`
		} `json:"settings"`
	} `json:"tokenColors"`
}
